#ifndef MQL_AUTO_FORWARDS_INCLUDED_7DF98814F69A1D26
#define MQL_AUTO_FORWARDS_INCLUDED_7DF98814F69A1D26
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in /Users/bunkheangheng/Desktop/Project/FinHubKh/finhub_journal/backend/ea/FinhubJournal_TradeSync.mq5

#line 28 "/Users/bunkheangheng/Desktop/Project/FinHubKh/finhub_journal/backend/ea/FinhubJournal_TradeSync.mq5"
void SyncHistory();
#line 122 "/Users/bunkheangheng/Desktop/Project/FinHubKh/finhub_journal/backend/ea/FinhubJournal_TradeSync.mq5"
void SendToEndpoint(string json, int count);
#line 145 "/Users/bunkheangheng/Desktop/Project/FinHubKh/finhub_journal/backend/ea/FinhubJournal_TradeSync.mq5"
string TimeToISO(datetime t);

#endif
