#ifndef MQL_AUTO_FORWARDS_INCLUDED_A7C79B9F70546537
#define MQL_AUTO_FORWARDS_INCLUDED_A7C79B9F70546537
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in /Users/bunkheangheng/Desktop/Project/FinHubKh/finhub_journal/backend/ea/nXuu_TradeSync.mq5

#line 31 "/Users/bunkheangheng/Desktop/Project/FinHubKh/finhub_journal/backend/ea/nXuu_TradeSync.mq5"
void SyncHistory();
#line 125 "/Users/bunkheangheng/Desktop/Project/FinHubKh/finhub_journal/backend/ea/nXuu_TradeSync.mq5"
void SendToEndpoint(string json, int count);
#line 149 "/Users/bunkheangheng/Desktop/Project/FinHubKh/finhub_journal/backend/ea/nXuu_TradeSync.mq5"
string TimeToISO(datetime t);

#endif
